FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run

# Defines our working directory in container
WORKDIR /usr/src/app

RUN "npm install discord.js"

COPY bot.js /usr/src/app

CMD ["node", "bot.js"]
